# Generated by Django 3.2.6 on 2021-08-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_alter_domainsearched_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainending',
            old_name='id',
            new_name='sno',
        ),
        migrations.RenameField(
            model_name='domainsearched',
            old_name='id',
            new_name='sno',
        ),
    ]
