# Generated by Django 3.2.6 on 2021-08-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_auto_20210826_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainsearched',
            name='searches',
            field=models.TextField(),
        ),
    ]
