# Generated by Django 3.2.6 on 2021-08-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverified',
            name='verification_id',
            field=models.CharField(default='XXXX', max_length=100),
        ),
        migrations.AlterField(
            model_name='userverified',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
